#应用名称及验证账号
spring: 
  application: 
    name: service-valuation
#  security: 
#    user: 
#      name: root
#      password: root  profiles:    active:    - 8060

#注册中心
eureka: 
  client:
    #设置服务注册中心的URL
    service-url:                      
      defaultZone: http://root:root@eureka-7900:7900/eureka/
  
    
#Admin监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
---
spring:  profiles: 8060
server: 
  port: 8060
---
spring:
  profiles: 8061
server: 
  port: 8061       