#服务端口
server: 
  port: 8084

#应用名称及验证账号
spring: 
  application: 
    name: api-listen-order
  #是否向server注册服务，默认true
  cloud:    service-registry:      auto-registration:        enabled: true

#注册中心
eureka: 
  client:
    #设置服务注册中心的URL
    service-url:                      
      defaultZone: http://root:root@localhost:7900/eureka/
  instance: 
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    lease-renewal-interval-in-seconds: 1      
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 1   
    hostname: localhost
    #true表示，将自己的ip注册到Eureka Server上，不配置或false表示将所在操作系统hostname注册到eureka server上。
    prefer-ip-address: true
    instance-id: service-wallet
    metadata-map:
      user.name: root
      user.password: root
      yueyi: 2019
    
#Admin监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS