#服务端口
server: 
  port: 8003

#应用名称及验证账号
spring: 
  application: 
    name: service-app-update
  #数据库连接配置
  datasource: 
    #配置当前使用的数据源的操作类型
    type: com.alibaba.druid.pool.DruidDataSource                          
    #配置MySQL的驱动程序类
    driver-class-name: com.mysql.cj.jdbc.Driver                             
    #数据库连接地址
    url: jdbc:mysql://localhost:3306/online-taxi?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #数据库连接用户名
    username: root                                                        
    #数据库连接密码
    password: root                                                        
    #进行数据库连接池的配置
    dbcp2:          
      #初始化提供的连接数                                                      
      initial-size: 5    
      #数据库连接池的最小维持连接数                                                 
      min-idle: 5          
      #最大的连接数                                               
      max-total: 5 
      #等待连接获取的最大超时时间                                                       
      max-wait-millis: 200                                                
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      
#mybatis配置
mybatis:
  #mybatis配置文件所在路径
  config-location: classpath:mybatis/mybatis.cfg.xml 
  #定义所有操作类的别名所在包
  type-aliases-package: com.online.taxi.common
  #所有的mapper映射文件  
  mapper-locations:             
  - classpath:mybatis/mapper/*.xml  

logging:  level:    root: info  
    com.online.taxi.app.dao: debug
    
#Admin监控
management:
  endpoints:
    web:
      #将所有的端点对web暴露，因为有jmx和web的区别
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS