#单节点
#应用名称及验证账号
spring: 
  application: 
    name: eureka
    
  security: 
    user: 
      name: root
      password: root
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server: 
    #关闭自我保护
    enable-self-preservation: false
    #清理间隔时间
    eviction-interval-timer-in-ms: 5000
logging:  level:    root: info
---
spring:
  profiles: 7900
server: 
  port: 7900
eureka:
  instance:#    prefer-ip-address: true
#    ip-address: 192.168.0.103
    hostname: eureka-7900
  client:
    service-url:                      
      defaultZone: http://root:root@localhost:7900/eureka/
