#服务端口
server: 
  port: 9002

#应用名称及验证账号
spring: 
  application: 
    name: api-driver    admin:      enabled: true
  redis:    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000
  #zipkin
  zipkin:
    base-url: http://localhost:9411/
    #采样比例1，百分之八采样
  sleuth:
    sampler:
      rate: 1  #注册中心
eureka: 
  client:
    #设置服务注册中心的URL
    service-url:                      
      defaultZone: http://root:root@eureka-7900:7900/eureka/
  instance: 
    hostname: localhost
      
    
##手写ribbon        
#service-sms: 
#  ribbon: 
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    eureka: 
#      enable: false
#    listOfServers: localhost:8002,localhost:8003

service-sms: 
  ribbon: 
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    #service-valuation: 
#  ribbon: 
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:  eager-load:
    enabled: true    clients:    - SERVICE-SMS#  http:#    client:#      enabled: false  
#  okhttp:#    enabled: false   

#Admin监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      ##默认是never
      show-details: ALWAYS
      enabled: true
          
logging:  level:    org.springframework: info