#服务端口
server: 
  port: 9001

#应用名称及验证账号
spring: 
  application: 
    name: api-passenger

#注册中心
eureka: 
#  server:
#    enable-self-preservation: false       #关闭保护机制
#    eviction-interval-timer-in-ms: 2000   #剔除失效服务间隔,单位毫秒
  client:
    #设置服务注册中心的URL
    service-url:                      
      defaultZone: http://root:root@eureka-7901:7901/eureka/,http://root:root@eureka-7902:7902/eureka/,http://root:root@eureka-7903:7903/eureka/
  instance: 
    hostname: localhost
